language: php
os: linux

php:
  - 7.3
  - 7.4

env:
  global:
    - COMPOSER_FLAGS=""
    - COMPOSER_DISCARD_CHANGES=true
  jobs:
    - LARAVEL=5.5.* TESTBENCH=3.5.* PHPUNIT=6.*
    - LARAVEL=5.6.* TESTBENCH=3.6.* PHPUNIT=7.*
    - LARAVEL=5.7.* TESTBENCH=3.7.* PHPUNIT=7.*
    - LARAVEL=5.8.* TESTBENCH=3.8.* PHPUNIT=8.*
    - LARAVEL=6.* TESTBENCH=4.* PHPUNIT=8.*
    - LARAVEL=7.* TESTBENCH=5.* PHPUNIT=^8.5
    - LARAVEL=8.* TESTBENCH=6.* PHPUNIT=^9

    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.5.* TESTBENCH=3.5.* PHPUNIT=6.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.6.* TESTBENCH=3.6.* PHPUNIT=7.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.7.* TESTBENCH=3.7.* PHPUNIT=7.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.8.* TESTBENCH=3.8.* PHPUNIT=8.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=6.* TESTBENCH=4.* PHPUNIT=8.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=7.* TESTBENCH=5.* PHPUNIT=^8.5
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=8.* TESTBENCH=6.* PHPUNIT=^9

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - travis_retry composer self-update

install:
  - composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" "phpunit/phpunit:${PHPUNIT}" --prefer-source --no-interaction --no-suggest
  - composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
